name: Build STM32 Project IOT
run-name: ${{ github.actor }} is running out GitHub Actions to STM32 IOT Project🚀
on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up ARM GCC Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi

    - name: Build project
      run: make -C Debug

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: STM32-IOT-Build
        path: iot/build/*.bin

