name: Lint and Build STM32 Project

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Super-Linter (warnings only)
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: "^(Drivers|Middlewares|Core/Startup|Debug)/"
          LINTER_C_DISABLED: false
          LINTER_CPP_DISABLED: false
          LINTER_MARKDOWN_DISABLED: false

  build:
    name: Build STM32 Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ARM GCC Toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi make

      - name: Build firmware
        run: |
          make -j$(nproc)

      - name: Verificar arquivos ELF/HEX
        run: |
          echo "Arquivos .elf encontrados:"
          find . -maxdepth 1 -name '*.elf'
          echo "Arquivos .hex encontrados:"
          find . -maxdepth 1 -name '*.hex'

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            *.elf
            *.hex
